/*
 * generated by Xtext
 */
package org.fuin.dsl.cqrs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CqrsDSLUiModule extends org.fuin.dsl.cqrs.ui.AbstractCqrsDSLUiModule {
	public CqrsDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
