/*
 * generated by Xtext
 */
package org.fuin.dsl.cqrs.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCqrsDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.fuin.dsl.cqrs.cqrsDSL.CqrsDSLPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.fuin.org/dsl/ddd/DomainDrivenDesignDsl"));
		return result;
	}
}
