/*
* generated by Xtext
*/
package org.fuin.dsl.cqrs;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CqrsDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.fuin.dsl.cqrs.ui.internal.CqrsDSLActivator.getInstance().getInjector("org.fuin.dsl.cqrs.CqrsDSL");
	}
	
}
