/**
 * generated by Xtext
 */
package org.fuin.dsl.cqrs.ui.contentassist;

import org.fuin.dsl.cqrs.ui.contentassist.AbstractCqrsDSLProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CqrsDSLProposalProvider extends AbstractCqrsDSLProposalProvider {
}
