/*
 * generated by Xtext
 */
package org.fuin.dsl.cqrs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CqrsDSLRuntimeModule extends org.fuin.dsl.cqrs.AbstractCqrsDSLRuntimeModule {

}
