/*
* generated by Xtext
*/
package org.fuin.dsl.cqrs;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CqrsDSLStandaloneSetup extends CqrsDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new CqrsDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

