/**
 * generated by Xtext
 */
package org.fuin.dsl.cqrs.validation;

import org.fuin.dsl.cqrs.validation.AbstractCqrsDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CqrsDSLValidator extends AbstractCqrsDSLValidator {
}
