/*
 * generated by Xtext
 */
package org.fuin.dsl.cqrs.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.fuin.dsl.cqrs.ui.internal.CqrsDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CqrsDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CqrsDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CqrsDSLActivator.getInstance().getInjector(CqrsDSLActivator.ORG_FUIN_DSL_CQRS_CQRSDSL);
	}
	
}
